// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6fbOZpYaYT41s5ND7I8Oaf5sj5zSlA-A',
    appId: '1:794901367340:web:25d0f07f623970dd4ddf89',
    messagingSenderId: '794901367340',
    projectId: 'smartplant-d3806',
    authDomain: 'smartplant-d3806.firebaseapp.com',
    databaseURL: 'https://smartplant-d3806-default-rtdb.firebaseio.com',
    storageBucket: 'smartplant-d3806.firebasestorage.app',
    measurementId: 'G-JPVDLHSX7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxOce25gtSOl5H81dI0AjbYaOHLTb9M_I',
    appId: '1:794901367340:android:7dd8f19dcd6908884ddf89',
    messagingSenderId: '794901367340',
    projectId: 'smartplant-d3806',
    databaseURL: 'https://smartplant-d3806-default-rtdb.firebaseio.com',
    storageBucket: 'smartplant-d3806.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoeCX-PaYCbG75b6HH2ZLTqS5H1x29FFo',
    appId: '1:794901367340:ios:b80f88172608349a4ddf89',
    messagingSenderId: '794901367340',
    projectId: 'smartplant-d3806',
    databaseURL: 'https://smartplant-d3806-default-rtdb.firebaseio.com',
    storageBucket: 'smartplant-d3806.firebasestorage.app',
    iosBundleId: 'com.example.smartPlantCommunicator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoeCX-PaYCbG75b6HH2ZLTqS5H1x29FFo',
    appId: '1:794901367340:ios:b80f88172608349a4ddf89',
    messagingSenderId: '794901367340',
    projectId: 'smartplant-d3806',
    databaseURL: 'https://smartplant-d3806-default-rtdb.firebaseio.com',
    storageBucket: 'smartplant-d3806.firebasestorage.app',
    iosBundleId: 'com.example.smartPlantCommunicator',
  );

}